### ISSUE TITLE
 json format 兼容普通的字符串,以避免一些泛型要重新判断

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-json#28]
json format 兼容普通的字符串,以避免一些泛型要重新判断

**Comment by venusdrogon** [comment]
```JAVA

net.sf.json.JSONException: A JSONObject text must begin with '{' at character 1 of 70E528D8283E30249C33DC5901307461
	at net.sf.json.util.JSONTokener.syntaxError(JSONTokener.java:499)
	at net.sf.json.JSONObject._fromJSONTokener(JSONObject.java:972)
	at net.sf.json.JSONObject._fromString(JSONObject.java:1201)
	at net.sf.json.JSONObject.fromObject(JSONObject.java:165)
	at com.feilong.json.jsonlib.JsonHelper.toJSONObject(JsonHelper.java:206)
	at com.feilong.json.jsonlib.JsonHelper.toJSON(JsonHelper.java:136)
	at com.feilong.json.jsonlib.JsonUtil.format(JsonUtil.java:617)
	at com.feilong.json.jsonlib.JsonUtil.format(JsonUtil.java:589)
	at com.feilong.json.jsonlib.JsonUtil.format(JsonUtil.java:215)
	at com.feilong.context.invoker.AbstractResponseStringBuilder.postBuild(AbstractResponseStringBuilder.java:81)
	at com.feilong.context.invoker.AbstractResponseStringBuilder.build(AbstractResponseStringBuilder.java:51)
	at com.feilong.tools.ccvideo.SpringCCVideoManagerTest.test(SpringCCVideoManagerTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:83)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:72)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:231)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:88)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:71)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:174)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)


```

**Comment by venusdrogon** [comment]
![image](https://user-images.githubusercontent.com/3479472/59705853-cd7bb480-9231-11e9-9986-618bbffe534b.png)
